name = "BruhPack"
author = "Bruhdows"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "219d7163c47ee214fe886bb4186181da7d249f5e0f642aa5bf9160404b741839"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
