name = "BruhPack"
author = "Bruhdows"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee6b38c1c2a2595debe17b6b68319d6166e059b16211220eaf0946e13b5712ee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
